ACTOR_DEFAULT_SOURCE = "header"
ACTOR_DEFAULT_REQUIRED = True
ACTOR_DEFAULT_MISSING_STATUS_CODE = 401
ACTOR_DEFAULT_MISSING_CODE = "UNAUTHORIZED"
ACTOR_DEFAULT_MISSING_MESSAGE = "Missing actor identity."
