SERVICE_DECORATOR_PHASE = {
    "Encode": "encode",
    "Decode": "decode",
}

SERVICE_DECORATOR_TRANSFORM_ERROR_CODE = "SERVICE_DECORATOR_TRANSFORM_ERROR"
SERVICE_DECORATOR_SAFE_ERROR_MESSAGE = "Data transform failed."
